## 1. 
MNIST 데이터셋으로 분류기를 만들어 테스트 세트에서 97% 정확도를 달성해보세요.   
Hint 
- KNeighborsClassifier가 이 작업에 아주 잘 맞습니다.   
- 좋은 하이퍼파라미터 값 찾기: Grid Search CV(weights와 n_neighbors)

In [44]:
from sklearn.datasets import fetch_openml
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

In [45]:
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target

In [46]:
X.shape

(70000, 784)

In [47]:
y.shape

(70000,)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [25]:
type(X_train)

numpy.ndarray

In [33]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, y_train)

KNeighborsClassifier()

In [34]:
param_grid = {'weights': ['distance', 'uniform'],'n_neighbors':[3,4,5,6]}

knn_clf = KNeighborsClassifier()
grid_search = GridSearchCV(knn_clf, param_grid, cv = 3)
grid_search.fit(X_train[:10_000], y_train[:10_000])

C:\Users\leehj\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\leehj\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 767, in _score
  File "C:\Users\leehj\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 444, in _passthrough_scorer
    "Use sklearn.metrics.get_scorer_names() "
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leehj\anaconda3\Lib\site-packages\sklearn\base.py", line 668, in score
  File "C:\Users\leehj\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py", line 237, in predict
    The fitted k-nearest neighbors classifier.
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\leehj\anaconda3\Lib\site-packages\sklearn\neighbors\_base.py", line 824, in kneighbors
    % type(n_neighbors)
          ^^^^^^^^^^^^^
  File

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 4, 5, 6],
                         'weights': ['distance', 'uniform']})

In [27]:
grid_search.best_params_

{'n_neighbors': 3, 'weights': 'distance'}

In [28]:
grid_search.best_score_

nan

In [29]:
grid_search.best_estimator_.fit(X_train, y_train)
tuned_accuracy = grid_search.score(X_test, y_test)
tuned_accuracy

AttributeError: 'NoneType' object has no attribute 'split'

In [7]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
X_train[0].reshape(28,28)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,  26, 255,  90,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  26,  26,   0,  13,  64, 138, 180, 199,  11,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         41, 224, 232, 207, 221, 253, 242, 162,  17,   0,   0,   0,   0,
          0,   0],
       [  

In [63]:
from scipy.ndimage import shift

def shift_image(arr, dy, dx):
    new = arr.copy()
    for image in arr:
        img = image.reshape(28,28)
        shifted_img = shift(img, [dy, dx], cval = 0).reshape([-1])
        new = np.vstack((new, shifted_img))
    return new[-1], new.shape

In [64]:
shift_image(X_train[:500],2,3)

(array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [56]:
X_train.shape

(56000, 784)

In [57]:
y_train.shape

(56000,)

In [58]:
new[:-5]

NameError: name 'new' is not defined